change rules to restrict to same repo

diff --git a/.github/workflows/enforce-pr-source.yml b/.github/workflows/enforce-pr-source.yml
--- a/.github/workflows/enforce-pr-source.yml
+++ b/.github/workflows/enforce-pr-source.yml
@@ -11,7 +11,12 @@ jobs:
     steps:
       - name: Check if source branch is develop
         run: |
-          if [[ "${{ github.head_ref }}" != "develop" ]]; then
-            echo "Error: Pull requests into 'master' must originate from the 'develop' branch."
+          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
+            echo "::error::Pull requests into 'master' must originate from the same repository."
+            exit 1
+          fi
+
+          if [[ "${{ github.event.pull_request.head.ref }}" != "develop" ]]; then
+            echo "::error::Pull requests into 'master' must originate from 'develop' or a 'feature/*' branch."
             exit 1
           fi
